### ISSUE TITLE
sevenseconds terminate because of request limit exceeded 

### ISSUE THREAD

**Issue by Raffo** [zalando-stups/sevenseconds#59]
```
time="2017-05-12T12:20:34.919412816Z" level=error msg="sevenseconds run #1 | [   foo|eu-central-1 | 0:01:46.465553] Traceback (most recent call last):"
time="2017-05-12T12:20:34.919472949Z" level=error msg="sevenseconds run #1 |   File "/usr/local/lib/python3.6/dist-packages/sevenseconds/helper/threading.py", line 21, in wrapper"
time="2017-05-12T12:20:34.919486833Z" level=error msg="sevenseconds run #1 |     self.function(*args)"
time="2017-05-12T12:20:34.919505612Z" level=error msg="sevenseconds run #1 |   File "/usr/local/lib/python3.6/dist-packages/sevenseconds/config/__init__.py", line 111, in configure_account_region"
time="2017-05-12T12:20:34.919534879Z" level=error msg="sevenseconds run #1 |     vpc = configure_vpc(account, region)"
time="2017-05-12T12:20:34.919546666Z" level=error msg="sevenseconds run #1 |   File "/usr/local/lib/python3.6/dist-packages/sevenseconds/config/vpc.py", line 49, in configure_vpc"
time="2017-05-12T12:20:34.919740148Z" level=error msg="sevenseconds run #1 |     ami_id = get_base_ami_id(account, region)"
time="2017-05-12T12:20:34.919784897Z" level=error msg="sevenseconds run #1 |   File "/usr/local/lib/python3.6/dist-packages/sevenseconds/config/ami.py", line 7, in get_base_ami_id"
time="2017-05-12T12:20:34.919882587Z" level=error msg="sevenseconds run #1 |     permit_base_image(account, region)"
time="2017-05-12T12:20:34.919891677Z" level=error msg="sevenseconds run #1 |   File "/usr/local/lib/python3.6/dist-packages/sevenseconds/config/ami.py", line 53, in permit_base_image"
time="2017-05-12T12:20:34.919910156Z" level=error msg="sevenseconds run #1 |     if len(image.describe_attribute(Attribute='launchPermission')['LaunchPermissions']) < 10:"
time="2017-05-12T12:20:34.919986071Z" level=error msg="sevenseconds run #1 |   File "/usr/local/lib/python3.6/dist-packages/boto3/resources/factory.py", line 520, in do_action"
time="2017-05-12T12:20:34.919997958Z" level=error msg="sevenseconds run #1 |     response = action(self, *args, **kwargs)"
time="2017-05-12T12:20:34.920010144Z" level=error msg="sevenseconds run #1 |   File "/usr/local/lib/python3.6/dist-packages/boto3/resources/action.py", line 83, in __call__"
time="2017-05-12T12:20:34.920148088Z" level=error msg="sevenseconds run #1 |     response = getattr(parent.meta.client, operation_name)(**params)"
time="2017-05-12T12:20:34.920177356Z" level=error msg="sevenseconds run #1 |   File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 253, in _api_call"
time="2017-05-12T12:20:34.920188843Z" level=error msg="sevenseconds run #1 |     return self._make_api_call(operation_name, kwargs)"
time="2017-05-12T12:20:34.92019983Z" level=error msg="sevenseconds run #1 |   File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 557, in _make_api_call"
time="2017-05-12T12:20:34.920209719Z" level=error msg="sevenseconds run #1 |     raise error_class(parsed_response, operation_name)"
time="2017-05-12T12:20:34.920220507Z" level=error msg="sevenseconds run #1 | botocore.exceptions.ClientError: An error occurred (RequestLimitExceeded) when calling the DescribeImageAttribute operation (reached max retries: 4): Request limit exceeded."
time="2017-05-12T12:20:34.920230795Z" level=error msg="sevenseconds run #1 | "
time="2017-05-12T12:20:34.920567816Z" level=error msg="sevenseconds run #1 | [   foo|eu-central-1 | 0:01:46.465879] An error occurred (RequestLimitExceeded) when calling the DescribeImageAttribute operation (reached max retries: 4): Request limit exceeded."
```

**Comment by tuxlife** [comment]
fixed with d3ad4c6eaf879be01bf36f7eaa6daa3b8108422f
